-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the `transform` role
DROP ROLE IF EXISTS TRANSFORM;
CREATE ROLE TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- We will use default COMPUTE_WH for this project as XS size is all we need 
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the `dbt` user and assign to role
DROP USER IF EXISTS dbt;
CREATE USER IF NOT EXISTS dbt
  LOGIN_NAME='dbt'
  TYPE=SERVICE
  RSA_PUBLIC_KEY="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+hxRV2hw8bFGDF5/HKI3
Kz4rnA1eJne/JGnSW+IAndE4WGOoiprl3Du2LoE5jDXGs81+hPxwIrNlwKx24Ku7
sAukvkpjfZ+SQTtQ3BA/dmpHK68in375FWOfIy7kzE4OuZzn0ja5Dcp2yYpZYpzT
rRD+iJH74h6zI/QOsoDI8ElUNIxlzrWc8uYhnZDMPog0tGeHhx6gmkpnjnWTvJTX
wyHrNOmGRNSezxOL9LTaWj61edUZq8RUV6zp7PkguDXUNQRxI5GZGQkNShEqDRG2
vF3GIVD+xWh78CVkxUstq38l3A6UM03q1m6ZRxtDa+ndFoe0RA/xv1mD4LxdHFin
yQIDAQAB" -- only public key exposed - our private key is safe :)
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_NAMESPACE='AIRBNB.RAW'
  COMMENT='DBT user used for data transformation';

GRANT ROLE TRANSFORM to USER dbt;

-- Set up permissions to role `transform`
-- for this project I am granting all permission although fine grained permission control is important, for the purposes of focusing on practicing airbyte I will keep as is.
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;

-- Create the user and permissions for Preset.io
USE ROLE ACCOUNTADMIN;

DROP ROLE IF EXISTS REPORTER;
CREATE ROLE REPORTER;

DROP USER IF EXISTS PRESET;
CREATE USER PRESET
  LOGIN_NAME='preset'
  TYPE=SERVICE
  RSA_PUBLIC_KEY="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+hxRV2hw8bFGDF5/HKI3
Kz4rnA1eJne/JGnSW+IAndE4WGOoiprl3Du2LoE5jDXGs81+hPxwIrNlwKx24Ku7
sAukvkpjfZ+SQTtQ3BA/dmpHK68in375FWOfIy7kzE4OuZzn0ja5Dcp2yYpZYpzT
rRD+iJH74h6zI/QOsoDI8ElUNIxlzrWc8uYhnZDMPog0tGeHhx6gmkpnjnWTvJTX
wyHrNOmGRNSezxOL9LTaWj61edUZq8RUV6zp7PkguDXUNQRxI5GZGQkNShEqDRG2
vF3GIVD+xWh78CVkxUstq38l3A6UM03q1m6ZRxtDa+ndFoe0RA/xv1mD4LxdHFin
yQIDAQAB"
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=REPORTER
  DEFAULT_NAMESPACE='AIRBNB.DEV'
 COMMENT='Preset user for creating reports';

GRANT ROLE REPORTER TO USER PRESET;
GRANT ROLE REPORTER TO ROLE ACCOUNTADMIN;
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE REPORTER;
GRANT USAGE ON DATABASE AIRBNB TO ROLE REPORTER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE REPORTER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA AIRBNB.DEV to ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AIRBNB.DEV to ROLE REPORTER;


